name: Breads of the World
favicon: null
layout_spectrum: 0.6865943064913154
typography_spectrum: 0.19439456472173333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#585743'
    - '#31241e'
    - '#e2e5ec'
    - '#babec1'
  brandStrength: 0.12850065412931144
  lightness: 0.02987127425149083
  saturation: 0.6941217554267496
  rhythmicContrast: 0.4265587441623211
purpose: []
