name: Breads of the World
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19439456472173333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#110d0a'
    - '#ba8853'
    - '#703a20'
    - '#e851b0'
  brandStrength: 0.12850065412931144
  lightness: 0.02987127425149083
  saturation: 0.6941217554267496
  rhythmicContrast: 0.4265587441623211
purpose: []
