name: Breads of the World
favicon: null
layout_spectrum: 0.6865943064913154
typography_spectrum: 0.19439456472173333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.12850065412931144
  lightness: 0.02987127425149083
  saturation: 0.6941217554267496
  rhythmicContrast: 0.4265587441623211
purpose: []
